omgnetwork/plasma-contracts

.gitignore, setup.py
Bumps Web3.py version to 4.5.0 for Python 3.7 support. Small change to gitignore to handle multiple `env*` folders.
=> Add support for Python 3.7

plasma_core/utils/deployer.py, setup.py, tests/conftest.py
Main idea - to use single building tool for both contract tests and production node.
In PR for use in production plasma chain, also is likely to be used in fee-burner.
package: https://pypi.org/project/py-solc-simple/
source: https://github.com/paulperegud/py_solc_simple/
=> Break out builder for contracts into separate package

contracts/RootChain.sol
Otherwise attacking token can be used to produce deposit block with blknum ending in 000. This can be exploited by attacker to create a situation when operator is spending the deposit which later disappears. Depending on implementation, this has a potential of invalidating of chain in eyes of client nodes.
=> prevent exploitation of `deposit` and `depositFrom` via re-entrance attack

contracts/RootChain.sol, testlang/testlang.py, tests/contracts/root_chain/test_deposit.py
This closes griefing vector where attacker uses owner's allowance to create multiple utxos on plasma chain. Very mild attack.
=> RootChain: only token owner can make a deposit

contracts/PriorityQueue.sol, contracts/PriorityQueueFactory.sol, contracts/PriorityQueueLib.sol, contracts/RootChain.sol, tests/conftest.py, tests/contracts/priority_queue/test_priority_queue.py, tests/contracts/root_chain/test_init.py, tests/contracts/root_chain/test_tokens.py
Our main contract no longer deploys - it reaches gas limit. Breaking up PriorityQueue into library that is deployed independently will help decrease RootChain's deployment gas cost.
TODO: actually deploy library in separate transaction. This probably requires changes in our building process.
=> Rework priority queue as library

contracts/RootChain.sol, tests/contracts/root_chain/test_challenge_in_flight_exit_input_spent.py, tests/contracts/root_chain/test_challenge_in_flight_exit_output_spent.py, tests/contracts/root_chain/test_respond_to_non_canonical_challenge.py
While all of those constitute reckless behavior and can be overridden by their first-period-only counterparts, the limitation is superfluous and makes testing harder.
=> feat: allow spent input, output challenges and `respondToNonCanonical` in first period

contracts/PlasmaCore.sol, contracts/PlasmaCoreTest.sol, contracts/RootChain.sol, tests/contracts/rlp/test_plasma_core.py
outputId is now UTXO position, which makes a clear distinction
between, what was previously called,  outputId and outputIndex
=> style: provide consistent names

Makefile, contracts/PlasmaCore.sol, contracts/PlasmaCoreTest.sol, contracts/RootChain.sol, plasma_core/constants.py, plasma_core/transaction.py, testlang/testlang.py, tests/conftest.py, tests/contracts/rlp/test_plasma_core.py, tests/contracts/root_chain/test_challenge_in_flight_exit_input_spent.py, tests/contracts/root_chain/test_challenge_in_flight_exit_not_canonical.py, tests/contracts/root_chain/test_challenge_in_flight_exit_output_spent.py, tests/contracts/root_chain/test_challenge_standard_exit.py, tests/contracts/root_chain/test_fee_exit.py, tests/contracts/root_chain/test_piggyback_in_flight_exit.py, tests/contracts/root_chain/test_process_exits.py, tests/contracts/root_chain/test_respond_to_non_canonical_challenge.py, tests/contracts/root_chain/test_start_in_flight_exit.py, tests/contracts/root_chain/test_start_standard_exit.py
We need to prevent possibility of double-spend via combining standard exit with in-flight exit. Text below describes possible flows and proposed solutions.
Proposed solution preserves the rule "Honest me can SE provided data
availability".
SE = standard exit
IFE = in-flight exit
1. SE on input -> IFE
=> contract: IFE challenges SE (~ +30k gas)
2. SE on input, finalized -> IFE
=> contract: IFE is non-canonical and can't be canonized; input is marked
as done (req. additional flag on IFE?)
3. IFE -> SE on input
=> game: standard SE challenge using IFE as spend
4. IFE, finalized input -> SE on input
=> game: standard SE challenge using IFE as spend
5. SE on output -> IFE -> piggyback output
-> exit game if data availability? must know which IFEs are incl. and where.
Piggyback is challenged …
=> Interaction between MVP and MoreVP exits

contracts/RootChain.sol
In the comment, it mentioned checking input and the
implementation checks output. The comment was wrong.
fix #85
=> fix: fix comment and implement inconsistency

contracts/RootChain.sol, tests/contracts/root_chain/test_deposit.py
Current contract does not check the input of deposit tx
should be empty. As a result, currently user can fake any input
data to the deposit tx. This may lead to some unexpected behaviour,
eg. making an IFE exit_id not unique by mimicing another existing
transaction with the same input. We did not separate deposit exit id
from regular tx for IFE because it is assumed that deposit tx cannot IFE
due to sum(inputs) would be 0 < sum(outputs). However, if fake input
is possible, then the assumption would be wrong. 
This commit add check to deposit tx inputs on `blknum` to be 0,
which should be enough as block start with 1.
issue: https://github.com/omisego/plasma-contracts/issues/88
=> fix: inputs of deposit not checked

contracts/Eip712StructHash.sol, plasma_core/transaction.py, plasma_core/utils/eip712_struct_hash.py, testlang/testlang.py, tests/contracts/root_chain/test_challenge_standard_exit.py, tests/contracts/root_chain/test_start_standard_exit.py, tests/utils/test_eip712_vectors.py
With the assumption that on different Ethereum networks different deployer addresses will be used, this :pr: adds replay protection for plasma transactions.
=> Add current contract address to struct hashing 'eip_domain'

.gitignore, plasma_framework/contracts/Migrations.sol, plasma_framework/contracts/mocks/framework/modifiers/OperatedMock.sol, plasma_framework/contracts/src/framework/modifiers/Operated.sol, plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/migrations/1_initial_migration.js, plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/test/src/framework/modifiers/Operated.test.js, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/framework/registries/VaultRegistry.test.js, plasma_framework/truffle-config.js
This PR setup a new folder for abstract layer implementation with truffle and implements the registries for exit games and vaults.
In the test, I use [openzeppelin-test-helpers](https://github.com/OpenZeppelin/openzeppelin-test-helpers) thus brings in npm dev-dependency. 
- migration plan: [here](https://omisego.atlassian.net/wiki/spaces/RES/pages/46530800/Abstract+Layer+Migration+Plan?atlOrigin=eyJpIjoiMjFiZjEyNDc3MWYwNDI1NDg3OTE0ZGU2ZjhlY2IwMWUiLCJwIjoiYyJ9)
- design doc: [here](https://docs.google.com/document/d/1PSxLnMskjqje4MksmW2msSSg-GtZoBSMNYey9nEDvt8)
close: https://github.com/omisego/plasma-contracts/issues/117
truffle test
```
Contract: Operated
onlyOperator
✓ accepts call when it is from operator (84ms)
✓ rejects call when it is not from operator (66ms)
Contract: …
```
=> Plasma framework init + Registries implementation

plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/contracts/src/framework/PlasmaFramework.sol, plasma_framework/test/src/framework/ExitGameController.test.js, plasma_framework/test/src/framework/PlasmaFramework.test.js
This commit combines all existing compoenents into the final
PlasmaFramework code. Also add a missing feature in constructor
of ExitGameController.
truffle test
```
Contract: ExitGameController
constructor
✓ inits the queue for ETH
Contract: PlasmaFramework
constructor
✓ can set the min exit period (182ms)
```
=> feat: glue components into PlasmaFramework.sol

plasma_framework/contracts/mocks/utils/MerkleWrapper.sol, plasma_framework/contracts/mocks/utils/UtxoPosLibWrapper.sol, plasma_framework/contracts/src/utils/Merkle.sol, plasma_framework/contracts/src/utils/UtxoPosLib.sol, plasma_framework/test/helpers/merkle.js, plasma_framework/test/src/utils/Merkle.test.js, plasma_framework/test/src/utils/UtxoPosLib.test.js
- port `Merkle.sol` and add related test (test code thanks to @pik694 's POC code)
- Although there is a [Merkle lib in open-zepplin](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/bd13be9174943f3fa18896df4ac269f411143c7d/contracts/cryptography/MerkleProof.sol), but their code require the leaves to be sorted :(. So I don't think we can use that.
- add new lib `UtxoPosLib.sol` to handle utxo pos related functions. Originally in `PlasmaCore.sol`.
found open zeppelin's latest `ERCRecover` (they renamed `ECDSA`), so we don't need to port that :)
https://github.com/OpenZeppelin/openzeppelin-solidity/blob/bd13be9174943f3fa18896df4ac269f411143c7d/contracts/cryptography/ECDSA.sol
truffle test
```
Contract: Merkle
checkMembership
✓ should return true when proven included (41ms)
✓ …
```
=> Porting libraries: Merkle, UtxoPos

plasma_framework/contracts/src/exits/payment/PaymentStandardExitable.sol, plasma_framework/test/src/exits/utils/ExitableTimestamp.test.js
Applying gas cost optimizations suggested by @kevsul:
- change order of verifying that start of payment exit is valid, call most costly `require` as the last one
- do not use a temporary memory variable and put a structure directly into storage
=> refactor: optimize gas cost when starting standard payment exit

plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/framework/registries/VaultRegistry.test.js
We rely on empty value to check whether contracts are whitelisted/registered. Being able to register with empty value would break the assumption.
truffle test
```
Contract: ExitGameRegistry
registerExitGame
✓ rejects when trying to register with tx type 0
✓ rejects when trying to register with empty address
Contract: VaultRegistry
registerVault
✓ rejects when trying to register with vault id 0 (39ms)
✓ rejects when trying to register with an empty vault address (39ms)
```
=> fix: registery require non-empty key and value

plasma_framework/contracts/src/framework/BlockController.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/test/src/framework/BlockController.test.js
This PR changes `private` access modifiers into `public`, where the fields did have publicly available getters. We now use getters implicitly provided by Solidity.
=> Elevate private fields to public

plasma_framework/contracts/mocks/utils/UtxoPosLibWrapper.sol, plasma_framework/contracts/src/exits/utils/ExitId.sol, plasma_framework/contracts/src/utils/UtxoPosLib.sol, plasma_framework/test/helpers/utxoPos.js
We were using uint8 for output index which limits the tx output to
around 256. For DEX batch settlement this seems to be small. This commit
extends the field to uint16 and cap the output index to limit of
TX_OFFSET (10000).
closes #168
=> chore: use uint16 for output index

plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/framework/registries/VaultRegistry.test.js
Watcher would need to monitor new registered contracts as it can potentially be a byzantine event. This commit adds event to ExitGameRegistry and VaultRegistry.
closes: https://github.com/omisego/plasma-contracts/issues/141
=> feat: emit event on ExitGame and Vault registering

plasma_framework/contracts/mocks/framework/DummyExitGame.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/test/src/framework/ExitGameController.test.js
We need to flag output spent when exits are processed. We would
rely on this to resolve interaction between standard exit and
in-flight exit. Also, we would need this to solve the previous
problem that operator can steal fund.
This commit adds both batch and single api to flag. Batch api would
be used in in flight exit and single api for standard exit.
Meanwhile, as we moved some variables to public, which by default
comes with a getter function, remove the test for those getter.
- closes https://github.com/omisego/plasma-contracts/issues/171
- operator steal fund: https://git.io/fj1rz
```
Contract: ExitGameController
flagOutputsSpent
✓ should be able to flag single output (114ms)
✓ should be able to flag multiple outputs (103ms)
✓ should fail when not called by Exit Game contracts (54ms) …
```
=> feat: add flag output spent function

contracts/RootChain.sol, tests/contracts/root_chain/test_process_exits.py
We stated that the least 151 significant bits in exit id are reserved to
the tx's hash, but due to a bug it was no more that 105 bits of hash
used.
Shifting 256-bit left by 151 means that the 151 most significant bits
become zeroes and only 101 bits from the initial value are used (256 - 151 = 105).
=> Fix InFlightExit id miscalculation

plasma_framework/contracts/mocks/framework/DummyExitGame.sol, plasma_framework/contracts/mocks/framework/DummyVault.sol, plasma_framework/contracts/mocks/framework/registries/ExitGameRegistryMock.sol, plasma_framework/contracts/mocks/framework/registries/VaultRegistryMock.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/test/src/framework/BlockController.test.js, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/framework/registries/VaultRegistry.test.js
This is some follow up clean up with the PR: https://github.com/omisego/plasma-contracts/pull/176
1. rename 'onlyFromVault' -> 'onlyFromNonQuarantinedVault'
2. for 'onlyXXX' tests, in the mock registries, it returns bool instead of testing via emitting event. This simplifies the code.
3. Move test for "rejecting still quarantined vault" to be under 'submitDepositBlock'
=> refactor: tests for vault and exit game registry

plasma_framework/contracts/mocks/framework/DummyExitGame.sol, plasma_framework/contracts/mocks/framework/registries/ExitGameRegistryMock.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/contracts/src/framework/PlasmaFramework.sol, plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/package.json, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/test/src/framework/ExitGameController.test.js, plasma_framework/test/src/framework/PlasmaFramework.test.js, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js
Fixes #172 
New exit game must wait certain period to be able to take effect
Reuses the `Quarantine` library for exit games.
* ExitGameRegistry - checks that exit game is rejected when under quarantine
* ExitGameRegistry - checks that exit game passed when quarantine is over
* ExitGameController - rejects enqueue exit on quarantined ExitGame
=> Allow new exit games to be quarantined

plasma_framework/contracts/src/vaults/Erc20Vault.sol, plasma_framework/contracts/src/vaults/EthVault.sol, plasma_framework/contracts/src/vaults/Vault.sol, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js
Fixes #174 
__Solution description__
Proposed by @boolafish during review. :pray: 
Vault stores both deposit verifier addresses, lower index is earlier set. In-force verifier address is returned by getEffectiveDepositVerifier function, which checks whether _maturity timestamp_ is in future.
When new verifier contract is set, 0-index is assigned to current in-force, 1-index is this new one, maturity timestamp is set accordingly.
=> Deposit verifier waits certain period to take effect

.circleci/config.yml, plasma_framework/README.md, plasma_framework/codechecks.yml, plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/truffle-config.js
- adds eth-gas-reporter to help us profile our gas usage.
- https://www.npmjs.com/package/eth-gas-reporter
- I do find a down side of setting this, the unit test speed become slower : (
- without reporter: truffle test  42.05s user 3.95s system 52% cpu 1:26.89 total
- with reporter: truffle test  72.68s user 43.38s system 60% cpu 3:11.32 total
- thus 2~3 times slower for current tests.
[update @2019.08.06]
- apply @kevsul's comment, use env variably to turn on reporter.
- add README for general dev setup + `MOCHA_REPORTER` env var setup.
- run `npm audit fix` as it shows warning.
- add integration with CodeChecks to show "Gas Usage" in PR. (See the CI part below in this PR)
- add `CC_SECRET` env inside circle ci for plasma-contract (required by CodeChecks).
Please see the CI part of this …
=> add eth-gas-reporter to our test

plasma_core/block.py, plasma_core/constants.py, plasma_core/transaction.py, requirements.txt, setup.py, testlang/testlang.py, tests/contracts/rlp/test_plasma_core.py, tests/contracts/rlp/test_rlp.py, tests/contracts/root_chain/test_process_exits.py, tests/contracts/root_chain/test_start_in_flight_exit.py
Upgrade the RLP encoding library to the latest version, so that we can continue with other upgrades and switching into `plasma-framework`. 
The code must have changed a little, as the API of the lib has changed.
Refers to  #28 
I took a little different approach and applied some of the comments that appeared there in a CR.
=> Upgrade Python RLP encoding library to v1

plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/vaults/Erc20Vault.sol, plasma_framework/contracts/src/vaults/EthVault.sol, plasma_framework/contracts/src/vaults/Vault.sol, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js
Fixes #186 
Vaults uses similar to ExitGameRegisty's modifier `onlyFromNonQuarantinedExitGame`. Info about exit games quarantines are retrieved from `framework` (which extends `ExitGameRegistry`)
=> Withdraw can be called only by known, non-quarantined exit games

plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/contracts/src/framework/utils/PriorityQueue.sol, plasma_framework/test/src/framework/ExitGameController.test.js
Make exits traceable in the priority queue by emitting an `ExitQueued` event that contains the exit's `uniquePriority`
```
Contract: ExitGameController
enqueue
✓ emits an ExitEnqueued event
find exit in the priority queue
✓ should be able to find the exit in the priority queue 
```
Closes: #198
=> feat: emit ExitQueued event on enqueue

plasma_framework/contracts/src/exits/payment/PaymentInFlightExitable.sol, plasma_framework/contracts/src/exits/payment/PaymentStandardExitable.sol, plasma_framework/contracts/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.sol, plasma_framework/test/src/exits/payment/PaymentStandardExitable.test.js, plasma_framework/test/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.test.js
Signature of `IPaymentSpendingCondition.verify` was controversial because it requires 2 arguments for parameters `utxoPos` and `outputId`.
@pdobacz help me to figure out the meaning of these two :point_up: and that they are both needed there.
So as I'm understanding the matter at the moment (assuming spending condition for Payment transaction):
* Spending condition responsibility is to check: 
* that provided transaction spends provided input,
* and provided guard unlocks utxo for spending (in old words: owner of utxo signs tx)
* Spending condition is registered for concrete Tx type so it knows how to decode passed transaction,
* meaning of `outputId` is an input pointer to check that provided tx indeed spends that input 
`tx.inputs[inputIndex] == expected_input_pointer`
* meaning of …
=> Figure out better use spending condition

truffle-config.js
Local geth would start the chain with gas limit around 600000. Even passing
in some flags to set the target block gas limit it would still take some time
for the geth to adjust to such block gas limit. Default truffle is using gas
of 6721975 which would need to wait for the geth to increase its gas limit.
This commit alter the gas to 6000000 for faster local development experience.
closes: https://github.com/omisego/plasma-contracts/issues/199
run the following commands in two terminals:
```
ganache-cli -gaslimit 620000
```
```
npx truffle migrate --network local --reset
```
For environment variable: `.env` file
```
AUTHORITY_PASSPHRASE=ThisIsATestnetPassphrase
MIN_EXIT_PERIOD=600
```
=> feat: set default gas to 6000000 for local network

plasma_framework/contracts/mocks/exits/payment/routers/PaymentInFlightExitRouterMock.sol, plasma_framework/contracts/src/exits/payment/PaymentExitDataModel.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol
Since there are still some space to fit in a 32bytes slot to pack with the
uint64 exitStartTimestamp. Make it a bool for clearer readibility.
=> refactor: use bool for isFinalized in IFE

plasma_framework/contracts/src/framework/BlockController.sol, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/test/src/framework/BlockController.test.js
Fixes #233 
This :pr: separates `authority` address from the `operator` address.
Where:
- `authority` - an address which publishes new plasma blocks on the Ethereum
- `operator` - an address which deployed `PlasmaFramework` contract and is allow to register components to it such as Exit games, Vaults ...
It's worth to further separate `operator aka maintainer` from the `deployer` address - but this effort failed because of circular dependencies see: #239
=> Separation of maintainer and authority addresses

plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/test/helpers/ife.js, plasma_framework/test/src/exits/payment/PaymentChallengeIFENotCanonical.test.js
Fixes #162 
```
Contract: PaymentInFlightExitRouter
...
response to non-canonical challenge
when successfully responded to non-canonical challenge
✓ should emit InFlightExitChallengeResponded event (40ms)
✓ should set isCanonical back to true (66ms)
✓ should set bond owner to caller (59ms)
✓ should set oldest competitor position to response position (59ms)
is unsuccessful and
✓ fails when in-flight exit does not exists
✓ fails when in-flight transaction is not younger than competitor
✓ fails when in-flight transaction is not included in block (44ms)
```
=> 162 respond to noncanonical challenge

plasma_framework/contracts/src/transactions/PaymentTransactionModel.sol, plasma_framework/test/src/transactions/PaymentTransactionModel.test.js
Fixes #189 
This change requires that rlp-encoded transaction contains 4 fields: type, inputs, outputs & metadata.
Metadata is decoded to `bytes32`.
By an accident we always passing 32-zero bytes as [metadata from truffle tests](https://github.com/omisego/plasma-contracts/blob/ae4545c504ce7ca680d26cbccd36e575d66c59a7/plasma_framework/test/helpers/transaction.js#L30) so no changes requires in tests.
=> Makes metadata field mandatory for rlp-encoded tx

plasma_framework/contracts/src/framework/interfaces/IExitProcessor.sol
We had some discussion about the naming on whether it should be 'token' or something else.
Since there is no general consensus on the naming plus etherscan is using the word 'token' pretty broad anyway,
let's stick with it.
discussion: https://git.io/Je3qD
original issue: https://git.io/Je3qy
=> refactor: rename ercContract to token

plasma_framework/contracts/mocks/Imports.sol, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/truffle-config.js
Previously the e2e tests cannot be run due to gas limit on contract deployment. With optimizer
turned on, it can be deployed within gas limit.
Also, with latest compiler (0.5.11) it can compile without the previous issue tested in 0.5.8
closes #286
=> chore: turn on optimizer + reenable e2e tests

plasma_framework/contracts/src/transactions/eip712Libs/PaymentEip712Lib.sol, plasma_framework/test/helpers/paymentEip712.js
@pgebal I found a `bytes32 owner` in the precomputed eip712 TX_TYPE_HASH
=> fix: bytes32 owner -> bytes20 outputGuard in eip712 TX_TYPE_HASH

.circleci/config.yml, plasma_framework/.solcover.js, plasma_framework/README.md, plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/truffle-config.js
- Install and use the 0.7.0 beta version of solidity coverage. Somehow was not able to setup the coverage with 0.6 version in current master and it seems like others are migrating to the 0.7 beta already (such as open-zepplin)
- Update truffle to latest as the solidity coverage requires 0.5.31 which is higher then existing one.
- Update openzeppelin-test-helpers to latest as new truffle web3 dependency is incompatible with old one.
- Add "coverage" command in package.json. Can run coverage by "npm run coverag
- add coverage batch in README under `plasma_framework`
- install coverall
- use `package-lock` as circle ci cache key
- register `plasma-contract` to coverall
- link the folder `plasma_framework` to be the folder to get source code in coverall (done with coverall web UI)
- add …
=> 300 test coverage

plasma_framework/contracts/mocks/exits/SpendingConditionMock.sol, plasma_framework/contracts/mocks/exits/StateTransitionVerifierMock.sol, plasma_framework/contracts/mocks/utils/BondSizeMock.sol, plasma_framework/contracts/src/exits/utils/BondSize.sol, plasma_framework/contracts/src/exits/utils/TxFinalizationVerifier.sol, plasma_framework/contracts/src/vaults/Vault.sol, plasma_framework/test/src/exits/utils/BondSize.test.js, plasma_framework/test/src/utils/BondSize.test.js, plasma_framework/test/src/vaults/EthVault.test.js
- remove some solhint workaround as latest version fixes the bug. @kevsul 's PR has been merged and released.
- take care of BondSize boundary number, closes #296. End up not using `SafeMath` as it is really meaning less since it only protects `uint256` but we are using `uint128`. Instead, I add tests on that we support edge case of upgrade to max num of `uint128`.
- Add boundary of the BondSize to not be 0 during update. Thus with min size 1.
- fix bug around comparing time in BondSize. There was a bug when `now == effectiveUpdateTime` the update would be broken. Found this while trying to add tests for coverage : )
- make `depositVerifier` be updated right at `newDepositVerifierMaturityTimestamp`
---
- ~upgrade to solidity 0.5.12~ see this comment: …
=> Some Minor fixes

plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol, plasma_framework/test/src/exits/payment/PaymentChallengeIFEInputSpent.test.js, plasma_framework/test/src/exits/payment/PaymentChallengeIFENotCanonical.test.js, plasma_framework/test/src/exits/payment/PaymentChallengeIFEOutputSpent.test.js, plasma_framework/test/src/exits/payment/PaymentChallengeStandardExit.test.js, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/test/src/exits/payment/PaymentPiggybackInFlightExitOnInput.test.js, plasma_framework/test/src/exits/payment/PaymentPiggybackInFlightExitOnOutput.test.js, plasma_framework/test/src/exits/payment/PaymentProcessInFlightExit.test.js, plasma_framework/test/src/exits/payment/PaymentProcessStandardExit.test.js, plasma_framework/test/src/exits/payment/PaymentStartInFlightExit.test.js, plasma_framework/test/src/exits/payment/PaymentStartStandardExit.test.js, plasma_framework/test/src/exits/payment/PaymentUpdateBond.test.js, tests/tests_utils/plasma_framework.py
- Copy library events into the linked contracts (*Routers) so that they appear in the contract's abi and so are searchable. See https://blog.aragon.org/library-driven-development-in-solidity-2bebcaf88736/
- Changed the tests to use `expectEvent.inLogs` instead of `expectEvent.inTransaction`, this makes sure that the events are actually in the logs, and so can be found later by e.g `getPastEvents()`
=> fix: copy lib events into linked contracts

plasma_framework/test/helpers/merkle.js, plasma_framework/test/src/utils/Merkle.test.js
1. add coverage on the case when leaf on the right sibling
2. fix bug that merkle.js uses Math.log instead of Math.log2
issue: https://github.com/omisego/plasma-contracts/issues/343
=> tests: add coverage on merkle contract

plasma_framework/contracts/mocks/exits/utils/ExitableTimestampWrapper.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol, plasma_framework/contracts/src/exits/utils/ExitableTimestamp.sol, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/test/src/exits/payment/PaymentProcessInFlightExit.test.js, plasma_framework/test/src/exits/payment/PaymentStartStandardExit.test.js, plasma_framework/test/src/exits/utils/ExitableTimestamp.test.js
We made sure that the exitable timestamp is not computed based on the youngest input, but we take the furthest exitable timestamp of all inputs.
The issue still persists in the  RootChain contract.
Closes #216
=> 216 ife with invalid priority

plasma_framework/migrations/6_output_results.js
This should make life easier for @InoMurko 
This change basically saves the truffle migration outputs into `output.json` in the `build` folder. Much easier than parsing `stdout`.
=> truffle-migrations outputs saves to a file

plasma_framework/docs/integration-docs/integration-doc.md
This PR adds some docs for the standard exit and process exits, with examples and list of parameters. The examples are written in "pseudocode"/JS/Elixir, I can change the comment symbols to `//` if it's clearer. :)
The part about `utxoPos` can probably be extracted somewhere else.
=> Add exit game docs for standard exits and process exits

plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouterArgs.sol, plasma_framework/test/helpers/ife.js, plasma_framework/test/src/exits/payment/PaymentStartInFlightExit.test.js
We have changed the code to be using WireTransaction to parse txType instead.
This is some leftover that was not cleaned up.
closes: https://github.com/omisego/plasma-contracts/issues/338
=> feat: remove txType as input of the startIFE

plasma_framework/python_tests/tests/contracts/root_chain/test_long_run.py
We are running long running tests every Monday morning on `master` branch, but the tests are not ready yet, so I have disabled the tests so it does not make `master` branch to fail the test.
=> Silence long running tests

plasma_framework/Dockerfile
This PR adds a Dockerfile for an environment to deploy the contracts from. The intention behind this is to use a container and attempt to deploy the contracts to Rinkeby during CI/CD.
=> Add Dockerfile

plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouterArgs.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/test/src/exits/payment/PaymentChallengeIFENotCanonical.test.js
- Full test coverage for `PaymentChallengeIFENotCanonical`.
- Use `assert` instead of `require` in `ExitGameController` when verifying conditions that are expected to never fail.
References #389
=> 389 improve test coverage in exit game controller

plasma_framework/contracts/src/framework/utils/PriorityQueue.sol, plasma_framework/test/src/framework/utils/PriorityQueue.test.js
1. Privious tests was not able to hit all branches inside the code.
1. For `delMin` and `getMin`, fail the function with message.
- old coverall: https://coveralls.io/builds/26522392/source?filename=contracts/src/framework/utils/PriorityQueue.sol
- ref issue: https://github.com/omisego/plasma-contracts/issues/389
- closes: #391 
- new coverall: https://coveralls.io/builds/26610418/source?filename=contracts/src/framework/utils/PriorityQueue.sol
=> test: add tests for priority queue

README.md, plasma_framework/truffle-config.js
Currently the migration code on elixir-omg uses infura flag as a workaround to deploy contracts to local geth with specific private keys:
```yaml
plasma-deployer:
command:
- /bin/sh
- -c
- |
apk add --update curl
cd /home/node/plasma-contracts/plasma_framework
npx truffle migrate --network infura
environment:
- INFURA_URL=http://geth:8545
- INFURA_API_KEY=
```
This PR generalizes the `infura` config into a `remote` config where the private keys are expected as inputs for contract deployment.
```shell
$ REMOTE_URL=http://remote_provider_url \
DEPLOYER_PRIVATEKEY=0xaaaa... \
MAINTAINER_PRIVATEKEY=0xbbb... \
AUTHORITY_PRIVATEKEY=0xccc... \
npx truffle migrate --network remote
```
=> feat: convert truffle config from infura to remote

plasma_framework/contracts/mocks/exits/payment/PaymentInFlightExitModelUtilsMock.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentInFlightExitRouterMock.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentStandardExitRouterMock.sol, plasma_framework/contracts/src/exits/payment/PaymentInFlightExitModelUtils.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/test/src/exits/payment/PaymentInFlightExitModelUtils.test.js, plasma_framework/test/src/exits/payment/PaymentPiggybackInFlightExitOnInput.test.js, plasma_framework/test/src/exits/payment/PaymentPiggybackInFlightExitOnOutput.test.js
- Improves test coverage for `PaymentInFlightExitModelUtils` library to 100%.
- Moves `isFirstPiggybackOfTheToken` from `PaymentInFlightExitModelUtils` to `PaymentPiggybackInFlightExit` as it was used only there.
- Removes unused `clearOutputPiggyback` function.
References #389
=> test: add unit tests for PaymentInFlightExitModelUtils library

plasma_framework/contracts/src/framework/BlockController.sol, plasma_framework/test/src/framework/BlockController.test.js
That function was introduced to add the flexibility to move toward mechanism reorg protection
in the future. However, after discuss with the blockchain service team (elixir-omg) that feature
is not really on the priority list of implementing.
Also, auditor has sensed some issue with current way of updating authority. As a result of combination,
should just remove the function that we might not even needed to simply things.
closes #403
=> feat: remove setAuthority function

plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/contracts/src/vaults/Erc20Vault.sol, plasma_framework/contracts/src/vaults/EthVault.sol, plasma_framework/contracts/src/vaults/Vault.sol, plasma_framework/test/src/framework/registries/VaultRegistry.test.js, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js, plasma_framework/test/src/vaults/Vault.test.js
- Change quarantined period from 1 minExitPeriod to 2 for `Vault` and `DepositVerifier`. closes #412 
- Pull tests for set/get deposit verifier to new test file: `Vault.test.js`. It was under `EthVault.test.js` with comment saying it tests for both vaults.
- When deposit verifier is not set, ERC20 vault and Eth vault would fail with error message: `Deposit verifier has not been set`. And add test for this.
```
Contract: Erc20Vault
deposit
before deposit verifier is set
✓ should fail with error message
after all contracts are set
✓ should store erc20 deposit (135ms)
✓ should emit deposit event (140ms)
✓ should spend erc20 tokens from depositing user (132ms)
✓ should not store a deposit when the tokens have not been approved (76ms)
✓ should not store a deposit from user who does not match …
```
=> 412 extend vault quarantined period

plasma_framework/docs/integration-docs/integration-doc.md
Forgot to upgrade integ-doc when dealing https://github.com/omisego/plasma-contracts/issues/41
=> docs: update integ-doc that vault/depositVerifier takes 2 weeks

.circleci/config.yml
Somehow the CI starts to fail when installing dependency. This commit first remove the cache
usage in CI without fully digging into the root cause to unblock normal PR merging.
Example of CI failure: https://app.circleci.com/jobs/github/omisego/plasma-contracts/7045.
It is under a branch only adds document from master, so it is definitely not code change that breaks the CI. (This PR: https://github.com/omisego/plasma-contracts/pull/455)
=> chore: not using cache in python CI

plasma_framework/contracts/src/exits/registries/OutputGuardHandlerRegistry.sol, plasma_framework/contracts/src/exits/registries/SpendingConditionRegistry.sol, plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/test/src/exits/registries/OutputGuardHandlerRegistry.test.js, plasma_framework/test/src/exits/registries/SpendingConditionRegistry.test.js, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/framework/registries/VaultRegistry.test.js
Add more sanity check on the contract. Previously it was possible to register an address that the contract is not yet deployed. This commit uses the openzepplin library of 'isContract' function to do the sanity check.
lib: https://docs.openzeppelin.com/contracts/2.x/api/utils#Address-isContract-address-
closes: https://github.com/omisego/plasma-contracts/issues/410
=> fix: check all registration is a contract

plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol
While tracing through code, realize some events in library of controller is not defined in the router.
Reason of duplicating event definition, see: https://ethereum.stackexchange.com/questions/11137/watching-events-defined-in-libraries
=> fix: make sure events in lib states in the caller of lib too

.gitignore, plasma_framework/docs/design/payment-game-implementation-v1.md, plasma_framework/docs/design/tx-types-dependencies.md, plasma_framework/tenderly.yaml
Fix grammar and typos for the most part while reading the docs and trying to understand output and tx type:
**A question**:
Paragraph here: https://github.com/omisego/plasma-contracts/blob/cbe34d117a74772f6bf1d8798d47515c105a3e47/plasma_framework/docs/design/payment-game-implementation-v1.md#L34
* Am not sure about this statement -> `Also, output type is bound to the input type`. Could we give more information here?
* Totally don't know what that mean? `Currently the only output type that requires the spending tx's input to be using `utxoPos`. Potentially there can be output type deciding to be pointed by `outputId` instead in the future.`
**Generally**
It's hard to grasp all the scenarios of how tx types out put types are allowed to be used within the system. It be helpful to give some …
=> Improve readibility of payment game impl doc and tx types doc

plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouterArgs.sol, plasma_framework/test/endToEndTests/PaymentInFlightExit.e2e.test.js, plasma_framework/test/endToEndTests/PaymentStandardExit.e2e.test.js
- separate SE and IFE e2e test
- Add basic non canonical test
- Add competing IFE and resulting one canonical while another non-canonical. ref #470 
- Fix a bug in ChallengeCanonical. Using wrong index there, see [this commit](https://github.com/omisego/plasma-contracts/commit/079db9fcafa61897f87667e49d323973840df2f8#diff-b43a4342117885dc45ebcd47ad76b017). Was caught while writing e2e tests....
```
Contract: PaymentExitGame - In-flight Exit - End to End Tests
Given contracts deployed, exit game and both ETH and ERC20 vault registered
>>> TEST CASE: Canonical Basic
Given Alice deposited ETH
Given Alice started an canonical in-flight exit from transaction to Bob that is not mined
And owner of the output (Bob) piggybacks
✓ should emit InFlightExitOutputPiggybacked event
And someone processes …
```
=> IFE e2e test improvements

README.md
Fix running python tests `make` instructions in README file. 
Closes #485
=> Fix python tests make instructions in README

plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/test/src/exits/payment/controllers/PaymentPiggybackInFlightExitOnOutput.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentStartInFlightExit.test.js
PaymentExitGame was implemented to be able to support our restricted custody DEX design. As a result, the output guard preimage for an in-flight exit tx output might not be availible. Without the preimage, it was not possible to know the where this output is exiting fund to.
However, we have decided to reduce the scope of Payment Exit Game and remove the DEX supporting feature such as output guard mechanism to simplify the code base for initial launch. Given this, it becomes not necessary to save output owner (exitTarget) data in piggyback. It can be done in startIFE.
Do you think this change makes sense? @pgebal @kevsul @pik694 
It simplifies the code base and be more consistent. However, whenever we are introducing DEX supporting PaymentExitGame we would need to remember to bring this …
=> feat: save IFE output owner when startIFE instead

plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.test.js
Closes #522
changes:
* Use proper spending condition when challenging in-flight tx output exit
* Use proper spending condition when challenging in-flight tx input exit
=> fix: fix bug in getting spending condition for ife output and input challenge

plasma_framework/contracts/mocks/utils/RLPMockSecurity.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol
Fixes
```
,/home/circleci/repo/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol:47:5: Warning: Function state mutability can be restricted to pure
function buildController(
^ (Relevant source part starts here and spans across multiple lines).
,/home/circleci/repo/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol:48:5: Warning: Function state mutability can be restricted to pure
function buildController(
^ (Relevant source part starts here and spans across multiple lines).
,/home/circleci/repo/plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol:47:5: Warning: Function state mutability can be restricted to pure
function buildController(
^ (Relevant source part starts …
```
=> fix: fix compilation warnings regarding function state mutability

plasma_framework/contracts/mocks/transactions/PaymentTransactionModelMock.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol, plasma_framework/contracts/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.sol, plasma_framework/contracts/src/transactions/PaymentTransactionModel.sol, plasma_framework/docs/contracts/PaymentTransactionModel.md, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentStartInFlightExit.test.js, plasma_framework/test/src/transactions/PaymentTransactionModel.test.js
Closes #463
* Adds `PaymentTransactionModel.getOutput`function that gets an output for a given `outputIndex` and validates if `outputIndex` is not out of bounds
* Verifies if provided transaction position of in-flight transaction is non-zero when responding to a canonicity challenge
* Verifies if provided input index is not bigger than number of in-flight transaction inputs when challenging transaction canonicity
=> fix: implement additional checks

plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/python_tests/tests/contracts/root_chain/test_start_standard_exit.py
References #150
Changes:
* remove test that checks if it's impossible to start a standard exit after in-flight exit from the same output was started earlier , as it is not longer an expected behavior
* add test that checks if finalizing standard exit blocks finalizing of the same output exited via in-flight exit
=> tests: enable tests for start standard exit and start in-flight exit interactions

plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/docs/contracts/ExitGameController.md, plasma_framework/docs/contracts/PaymentInFlightExitRouter.md, plasma_framework/python_tests/tests/contracts/root_chain/test_piggyback_in_flight_exit.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/test/src/exits/utils/ExitId.test.js, plasma_framework/test/src/framework/ExitGameController.test.js
Closes #536 
Changes:
* fix failing on processing exits from in-flight transaction that has multiple distinct output tokens
* enable python tests for processing exits
=> fix: do not fail on processing exits from in-flight transaction that has multiple distinct output tokens

plasma_framework/python_tests/plasma_core/transaction.py, plasma_framework/python_tests/tests/contracts/root_chain/test_challenge_in_flight_exit_not_canonical.py, plasma_framework/python_tests/tests/contracts/root_chain/test_challenge_standard_exit.py, plasma_framework/python_tests/tests/contracts/root_chain/test_start_standard_exit.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py
Refers #150.
The following PR enables the tests that were skipped at the first run of enabling the tests.
The enabled tests are related to IFE and SE interaction and to EIP712 signatures.
=> 150 Enable omitted tests

plasma_framework/python_tests/tests/utils/test_eip712_vectors.py
Refers #150 
The following PR enables EIP712 struct hash test, so they run on ALD tx format.
=> Python EIP712 tests

plasma_framework/contracts/mocks/exits/SpyPlasmaFrameworkForExitGame.sol, plasma_framework/contracts/mocks/utils/PosLibWrapper.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouterArgs.sol, plasma_framework/contracts/src/exits/utils/MoreVpFinalization.sol, plasma_framework/contracts/src/framework/utils/ExitPriority.sol, plasma_framework/contracts/src/utils/Merkle.sol, plasma_framework/contracts/src/utils/PosLib.sol, plasma_framework/docs/contracts/ExitPriority.md, plasma_framework/docs/contracts/PosLib.md, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.test.js, plasma_framework/test/src/exits/utils/MoreVpFinalization.test.js, plasma_framework/test/src/utils/Merkle.test.js, plasma_framework/test/src/utils/PosLib.test.js
- Move the check of Merkle proof non empty to `checkMembership` function under `Merkle.sol`
- Add stricter range check in `PosLib`:
- `txIndex` should be max to 2^16 - 1. Also, use `uint16` for the field.
- Since there is a limit on ExitPriority that only 54 bits are reserved for `blockNum` + `txIndex`. Set the `MAX_BLOCK_NUM = ((2 ** 54 - 1) - MAX_TX_INDEX) / (BLOCK_OFFSET / TX_OFFSET);` and add check with that range.
- Add tests for edge values
=> add stricter range check for audit feedback

plasma_framework/docs/integration-docs/integration-doc.md
Following a request from @achiurizo, this adds a section elaborating handling of signed transactions in https://github.com/omisego/elixir-omg/ to the intregration docs transaction section.
I tried to follow conventions and blend in with the rest of the doc, but not sure if I got this right. Same goes for level of detail.
Also, there's an alternative location for this documentation: it could be put wherever the handling of such encoded signed transactions is done (`elixir-omg` currently). So if this doesn't fit in here, let's discuss.
=> docs: add section elaborating on signed transactions for chch/watcher

plasma_framework/contracts/src/utils/Merkle.sol, plasma_framework/test/helpers/merkle.js, plasma_framework/test/src/utils/Merkle.test.js
Merkle contract did not check whether index exceeds the max amount with the proof size. This can lead to issue where given different indexes that exceeds the size, it can still pass the check due to the implementation of for loop.
closes: #546
=> fix: mekle contract checks the index size

plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_delete_in_flight_exit.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py, plasma_framework/test/endToEndTests/PaymentStandardExit.e2e.test.js
Closes #549
Changes:
* add integration tests for `deleteNonPiggybackedInFlightExit`
* add test that checks if in-flight exit is not processed before exit period passes
=> test: add integration tests

.circleci/config.yml
The following PR reenables CI cache. We turned off the cache as python builds would fail due to the cache. 
I have reenabled truffle cache - used the code we used to use before.
I have reenabled python cache by using virtual env, as the old solution failed due to a collision between global python packages with project deps. 
Reenabling cache results in saving:
-  ~1 minute/truffle job 
- ~20s/python job.
Relates #377 
Relates #460
=> Use CI dependency caching 

plasma_framework/python_tests/Makefile, plasma_framework/python_tests/tests/contracts/root_chain/test_long_run.py
The following PR turns on overnight tests.
I have also added more verbose logging, so that it is easier to analyse if an error happened.
I have increased the has limit to `1 000 000`, as this is the amount that enables the test to pass and the issues related to load testing the contract will be taken care off soon.
Closes #217
=> 217 revive long running tests

plasma_framework/contracts/mocks/exits/SpyPlasmaFrameworkForExitGame.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentInFlightExitRouterMock.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentStandardExitRouterMock.sol, plasma_framework/contracts/mocks/framework/DummyExitGame.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessStandardExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/docs/contracts/ExitGameController.md, plasma_framework/docs/contracts/PaymentChallengeIFENotCanonical.md, plasma_framework/docs/integration-docs/integration-doc.md, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py, plasma_framework/test/endToEndTests/PaymentInFlightExit.e2e.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentProcessInFlightExit.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentProcessStandardExit.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentStartStandardExit.test.js, plasma_framework/test/src/framework/ExitGameController.test.js
Closes #533
Changes:
* rename `ExitGameController.isOutputSpent` to `ExitGameController.isOutputFinalized` to avoid confusion
* add section in integration docs explaining when in-flight transaction inputs/ouputs are not available to spend on child chain
=> docs: explain that in-flight transaction inputs/outputs are not available to spent on child chain

plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/test/src/framework/ExitGameController.test.js
It is invalid to do so as it would break the framework. Add explicit check instead of rely on
the correct implementation of ExitGame contracts.
closes: https://github.com/omisego/plasma-contracts/issues/559
=> feat: explicit check on enqueue with same priority

README.md, plasma_framework/contracts/src/framework/PlasmaFramework.sol, plasma_framework/migrations/2_deploy_plasma_framework.js, plasma_framework/package.json, plasma_framework/test/src/framework/PlasmaFramework.test.js
First version of https://github.com/omisego/plasma-contracts/issues/568
What was done?
- getters and setters on plasma framework
- setter can only be called by the maintainer
- migration calls the setter and pulls the plasma framework version from `package.json` and adds short git sha (7)
=> feature: track semver in contracts

CHANGELOG.md, plasma_framework/package.json
Reason: we can't "unrelease". We point to 1.0.x version in other places.
See: https://github.com/omisego/plasma-contracts/issues/561
Also, see rollback discussion here: https://github.com/omisego/plasma-contracts/pull/580
=> chore: bump version to 2.0.0, add CHANGELOG

CHANGELOG.md, README.md, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/test/endToEndTests/PaymentInFlightExit.e2e.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentProcessInFlightExit.test.js
- First fix for #584 , not closing the issue for other doc fixes and event improvement. Now all piggyback bond would be return while processIFE.
- Bumping version to 1.0.3 for this fix
=> ife stop eating wrong side bond

plasma_framework/docs/integration-docs/integration-doc.md
We need more information on transaction validity for referencing from watcher-specs. Example questions implementer might have are:
* where to look for details?
* how does it work?
=> docs: add more on transaction validity

.circleci/config.yml, plasma_framework/python_tests/tests/conftest.py, plasma_framework/python_tests/tests/contracts/root_chain/test_long_run.py
- reduce the iteration to 700, which would take 4 hours to run.
- increase the timeout for stability
closes #558 
enabled on CI temporary: https://app.circleci.com/jobs/github/omisego/plasma-contracts/10514
=> fix: slow test exceed circle ci timeout limit

plasma_framework/package-lock.json, plasma_framework/package.json
Got an dependency security alert from Github. Instead of just solving that, runs "npm audit fix" first and luckily the reported issue is covered as well. The reported dependency is minimist. It recommend to use version >= 1.2.2
- alert: https://github.com/omisego/plasma-contracts/network/alert/plasma_framework/package-lock.json/minimist/open
It is set to ^1.2.5 after `npm audit fix`.
```
▶ git show d9765efc91b9f657bc547cb1e85bbe3cc451072a | grep minimist
luckily the reported issue is covered as well. The reported dependency is minimist. It recommend to use version
alert: https://github.com/omisego/plasma-contracts/network/alert/plasma_framework/package-lock.json/minimist/open
+            "minimist": "^1.2.5"
+            "minimist": "^1.2.5"
+            "minimist": "^1.2.5"
- …
```
=> chore: npm audit fix

plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py
=> test: add test checking that inputs can not be exited from restarted ife after outputs finalized on processing the first ife

.circleci/config.yml, plasma_framework/truffle-config.js
- Checks whether token api exist (env var) before submitting request (For Codecheck and coverall). Since fork or private mirror repo would not have have the privilege to use them.
- Put coverage result and gas report to CircleCI artifact. So you can see the result there too.
- Let eth-gas-reporter output to file instead of stdout, allowing saving to artifact though the format is not great 🙁 (It prints prettily in shell with `less` or `cat` commands, but not in Ide or vim)
- coverage artifact example: [index.html](https://10778-138549951-gh.circle-artifacts.com/0/%7E/repo/plasma_framework/coverage/index.html), [circleCI link](https://app.circleci.com/pipelines/github/omisego/plasma-contracts/2068/workflows/828bb8bc-a5ca-4015-b109-131ace2a5736/jobs/10778/artifacts), this one is pretty good …
=> chore: check api token for coverage and gas report

.github/workflows/auto-pr-for-branch-syncing.yml, .github/workflows/dispatch-sync-to-private.yml, .github/workflows/sync-from-public-to-private.yml
Setup a auto sync Github action workflow to:
1. Whenever a new code pushed to `master` in public repo, it would dispatch an event to the private repo. (with event_type: `sync-from-public`)
1. Once received the dispatched event, the private repo would sync the `master` of the private with the public repo.
1. After the `master` branch is synced, it would automatically submit a PR to sync master back to the base branch of the private repo (`master-private`)
1. Created a new personal token of the lovely omisego-bot for this use. Set `HOUSE_KEEPER_BOT_TOKEN` as Github secret of the repo (both public & private)
Note that the dispatch event requires the workflow file to be in the base branch (usually master) to be able to work. see: https://github.community/t5/GitHub-Actions/repository-dispatch-n …
=> feat: auto syncing between public and private master

.circleci/config.yml, README.md, plasma_framework/config.js, plasma_framework/docs/deploying/deploying.md, plasma_framework/migrations/20_deploy_plasma_framework.js, plasma_framework/migrations/300_payment_v2_spending_condition_registry.js, plasma_framework/migrations/301_payment_v2_spending_conditions.js, plasma_framework/migrations/302_renounce_payment_v2_spending_condition_registery.js, plasma_framework/migrations/303_payment_v2_exit_game.js, plasma_framework/test/endToEndTests/PaymentV2Experiment.e2e.test.js
Add experimental payment v2 contract into the migration scripts.
Chosen the `300+` instead of `2000+` to be the migration index to not disrupt with the future deployment. So even if we run this migration script in existing deployed network. It would not take any effect.
Also, the deployment is guarded by env var `MULTI_EXIT_GAME_EXPERIMENT`. Need to be set to `true` to deploy the payment v2 contracts.
closes: https://github.com/omisego/new-tx-type-poc/issues/2
- turned on `MULTI_EXIT_GAME_EXPERIMENT` env var in CI and shows sth like: 
"Registering paymentV2ToPaymentV3Condition (0x963eC3789de59707309bAe6D955E44c7D0756513) to spendingConditionRegistry"
<details>
<summary> Experimental e2e test with `MULTI_EXIT_GAME_EXPERIMENT` env var </summary>
<pre>
Contract: PaymentExitGame - V2 …
=> feat: experimental payment v2 migration script

.circleci/config.yml, plasma_framework/python_tests/tests/conftest.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/python_tests/tests/tests_utils/assertions.py
Fixes recently failing tests and locks python circleci image in order to make builds deterministic.
Relates to #618
=> Stabilize python tests

plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/python_tests/Makefile, plasma_framework/python_tests/tests/conftest.py
- upgrade truffle version and run `npm install`
- run `npm audit`
- fix python linter issue, probably due to flake8 upgrade.
closes #592
=> chore: upgrade truffle

plasma_framework/contracts/poc/fast_exits/Liquidity.sol, plasma_framework/test/endToEndTests/FastExit.e2e.test.js
Closes https://github.com/omgnetwork/plasma-contracts/issues/629
=> [fast_exits] Pay exit bond to exit initiator

.circleci/config.yml, Dockerfile, plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/truffle-config.js
Seems like there is some dependency trouble. Try blindly solving it with npm audit fix.
closes #652
=> fix: truffle test failure

plasma_framework/python_tests/setup.cfg, plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py
The flaky python test setup was doomed to be flaky as there is no promise on the priority of 2 IFEs to be in the expected order of first come first serve. In fact the setup is more like broken where a non-canonical IFE should be challenged instead of processed as canonical. This PR change the test setup and rename the test to a non-canonical tx challenge scenario.
- ignore W503 standard for flake: https://www.flake8rules.com/rules/W503.html
see: https://github.com/omgnetwork/plasma-contracts/issues/606#issuecomment-678871977
fix: #606
=> fix: flaky python test for IFE process

.circleci/config.yml, .github/workflows/dispatch-sync-to-private.yml, .github/workflows/sync-from-public-to-private.yml
Since, the same infura account is used for both the Rinkeby deployment workflows, only one of them successfully succeeds. This could be because of infura having trouble to handle nonce. Using a nonce tracker also doesn't solve the problem. So Deploying asynchronously
=> Deploy Contracts serially and enable CI tests

plasma_framework/contracts/poc/fast_exits/Quasar.sol, plasma_framework/test/endToEndTests/QuasarExit.e2e.test.js
This includes-
1. Happy Withdrawal path with challenges
2. Updating Quasar Parameters
Yet to implement-
1. Byzantine condition and IFE-Claims
2. ERC-20 support
3. Anti front-running and service provider fee
=> Quasar Fast Exit: Implement withdrawal the happy path

plasma_framework/contracts/poc/fast_exits/Quasar.sol, plasma_framework/test/endToEndTests/QuasarExit.e2e.test.js, plasma_framework/test/src/poc/fast_exits/Quasar.test.js
Changes `safePlasmaBlockNum` to `safeBlockMargin` - the Quasar will not accept exits for outputs younger than the current plasma block minus `safeBlockMargin`.
=> feat: safe block margin

plasma_framework/contracts/mocks/framework/BlockControllerMock.sol, plasma_framework/contracts/poc/fast_exits/Quasar.sol, plasma_framework/contracts/poc/fast_exits/QuasarPool.sol, plasma_framework/test/endToEndTests/QuasarExit.e2e.test.js, plasma_framework/test/src/poc/fast_exits/Quasar.test.js
Includes - 
- IFE Claims
- separate deposit/withdraw (still based on one lender) #729 
- ERC20 support and simple anti-front running for challenges #732
=> Quasar Fast Exit: Add IFE Claims for Byzantine conditions

plasma_framework/contracts/poc/fast_exits/Quasar.sol
Making the ifeClaimData mapping in Quasar public so that the challenger can check if any IFEs are being claimed
=> quasar: make ifeClaimData public

plasma_framework/contracts/mocks/poc/QuasarPoolMock.sol, plasma_framework/contracts/poc/fast_exits/QToken.sol, plasma_framework/contracts/poc/fast_exits/Quasar.sol, plasma_framework/contracts/poc/fast_exits/QuasarPool.sol, plasma_framework/contracts/poc/fast_exits/interfaces/IQToken.sol, plasma_framework/contracts/poc/fast_exits/utils/Exponential.sol, plasma_framework/test/endToEndTests/QuasarExit.e2e.test.js, plasma_framework/test/src/poc/fast_exits/Quasar.test.js, plasma_framework/test/src/poc/fast_exits/QuasarPool.test.js
actual size of output that has to be fast exited
amount that can be withdrawn from the pool with the above output ( output_value - fees)
--> addCapacity() increases capacity by `supplied_funds`
----> obtainTicket() decreases capacity by `reserved_amount`
------> flushTicket() increases capacity back by `reserved_amount`
------> challengeClaim() can increase capacity back by `reserved_amount`
else, withdrawal successful, capacity reduced
--> repayPool() increases capacity by `output_value` of claimed outputs ( fee + `reserved_amount`)
--> withdrawFunds() decreases capacity by `supplied_funds` + fee(accumulated), [up till value of usable_capacity]
--> obtainTicket() adds bond value to contract
----> flushExpiredTicket() adds bond to unclaimed_bond reserve (stays in the contract)
------> …
=> quasar: Add fee and returns to quasar pool
