omgnetwork/plasma-contracts

contracts/PlasmaCore.sol, contracts/PlasmaCoreTest.sol, plasma_core/transaction_v2.py, tests/contracts/rlp/test_plasma_core.py
Adds `PlasmaCore.sol` which will be used by More Viable Plasma.
`transaction_v2.py` will eventually replace `transaction.py` but it'll be a breaking change so it'll be done in another PR.
Tests `PlasmaCore.sol`
@paulperegud
=> Add and test plasma core

testlang/testlang.py, tests/conftest.py, tests/contracts/root_chain/test_challenge_standard_exit.py, tests/contracts/root_chain/test_process_exits.py
=> tests for some transitions between states of the exit

docs/quantstamp-audit-3cc6097.md
- Add the final audit file
- Move to branching strategy described in [OIP-0004](https://github.com/omisego/OIP/blob/master/0004-ewallet-release-and-versioning.md)
TODO
=> Add Quantstamp Audit

contracts/RootChain.sol
Small interim extension of the event catalogue of `RootChain.sol`. No tests added because events aren't covered by tests yet (to fix later, for all the events).
Reason for change is being able to track exit finalizations and challenges from the child chian watcher and react.
=> feat: added ExitFinalized and ExitChallenged events

contracts/RootChain.sol, setup.py, tests/conftest.py, tests/contracts/root_chain/test_init.py
- lower gas usage thanks to RootChain.init() + tests
- some tidies and fixes
Allows `elixir-omg` to use these contracts in integration tests. 
Working towards `v0.1` (MoreVP)
=> Elixir omg morevp compatibility

contracts/RootChain.sol
=> feat: add missing event to respondToNonCanonicalChallenge function

contracts/ECRecovery.sol, tests/contracts/root_chain/test_challenge_standard_exit.py
=> check if ecrecover result isn't compared to zero address

contracts/Merkle.sol
This might be seen as a noob comment, but I think better safe than spend time figuring this out
=> docs: leave a note on proof mloading, just in case

README.md
From https://github.com/omisego/elixir-omg/blob/develop/docs/tesuji_blockchain_design.md -> https://github.com/omisego/elixir-omg/blob/master/docs/tesuji_blockchain_design.md
=> Update Tesuji File Location Link

contracts/RootChain.sol, tests/contracts/root_chain/test_process_exits.py
=> bug: don't emit ExitFinalized for challenged exits

contracts/RootChain.sol
=> chore: use more descriptive names for functions manipulating bit flags of IFEs

contracts/SignatureTest.sol
This is needed for https://github.com/omisego/elixir-omg/pull/656
=> Expose eip 712 hash public for tests

.gitignore, Dockerfile, README.md, contracts/Migrations.sol, migrations/1_check_authority_address.js, migrations/2_initial_migration.js, migrations/3_deploy_contracts.js, migrations/4_init_rootchain_contract.js, migrations/5_output_results.js, package-lock.json, package.json, truffle-config.js, truffle.js
Added Truffle support for deploying contracts
=> 115 deploy with truffle

.circleci/config.yml, plasma_framework/package-lock.json, plasma_framework/package.json
Now js tests are running on CircleCI
Closes #143
=> Add CircleCI configuration

plasma_framework/contracts/mocks/utils/BitsWrapper.sol, plasma_framework/test/src/utils/BitsLib.test.js
Fixes #193
No old tests were found to port.
=> Add new tests for Bits library

plasma_framework/contracts/src/exits/payment/PaymentExitGame.sol, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js
=> feat: make getting in-flight and standard exit ids public

plasma_framework/contracts/src/transactions/WireTransaction.sol, plasma_framework/contracts/src/transactions/outputs/PaymentOutputModel.sol, plasma_framework/test/helpers/transaction.js, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/test/src/exits/utils/ExitId.test.js, plasma_framework/test/src/transactions/WireTransaction.test.js
Let's return to the previous ordering.
More on the topic and motivations can be found in the following issue #250
=> Reorder transaction output fields

testlang/testlang.py
Fixes failing tests on master e.g. https://circleci.com/gh/omisego/plasma-contracts/2015
=> Fix failing submit block test

plasma_framework/contracts/src/framework/BlockController.sol, plasma_framework/contracts/src/vaults/Erc20Vault.sol, plasma_framework/contracts/src/vaults/EthVault.sol, plasma_framework/contracts/src/vaults/Vault.sol, plasma_framework/contracts/src/vaults/verifiers/EthDepositVerifier.sol, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js
Closes #260
As plasma framework contract does not understand strucutre of deposit events are emitted by specific vaults.
=> feat: emit events for sucessful Ethereum and ERC20 deposits

plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol
CI wasn't working well for this : (, which should fail but didn't.
https://circleci.com/gh/omisego/plasma-contracts/2352?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
This only fixes the code style but not fixing the CI issue.
=> style: remove unused var in PaymentChallengeIFEOutputSpent

plasma_framework/contracts/src/exits/payment/PaymentExitGame.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol, plasma_framework/contracts/src/utils/OnlyFromAddress.sol, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js
=> fix: restrict exit game processExit calls to only be called from exit game controller

plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeStandardExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessStandardExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol
=> docs: for controller main functions

plasma_framework/contracts/mocks/exits/SpyPlasmaFrameworkForExitGame.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentInFlightExitRouterMock.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentStandardExitRouterMock.sol, plasma_framework/contracts/mocks/exits/utils/ExitIdWrapper.sol, plasma_framework/contracts/mocks/framework/DummyExitGame.sol, plasma_framework/contracts/mocks/framework/ReentracyExitGame.sol, plasma_framework/contracts/mocks/framework/utils/ExitPriorityWrapper.sol, plasma_framework/contracts/src/exits/payment/PaymentExitDataModel.sol, plasma_framework/contracts/src/exits/payment/PaymentExitGame.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessStandardExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouterArgs.sol, plasma_framework/contracts/src/exits/utils/ExitId.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/contracts/src/framework/interfaces/IExitProcessor.sol, plasma_framework/contracts/src/framework/utils/ExitPriority.sol, plasma_framework/test/src/exits/payment/PaymentExitGame.test.js, plasma_framework/test/src/exits/utils/ExitId.test.js, plasma_framework/test/src/framework/ExitGameController.test.js, plasma_framework/test/src/framework/utils/ExitPriority.test.js
Closes #283. Please look to the issue for the explanation of the changes.
=> 283 Return to old exit priority schema

plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol
=> refactor: rename shadowed variables

plasma_framework/contracts/src/exits/payment/PaymentExitDataModel.sol, plasma_framework/contracts/src/exits/payment/PaymentExitGame.sol, plasma_framework/contracts/src/exits/payment/PaymentTransactionStateTransitionVerifier.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/contracts/src/exits/payment/outputGuardHandlers/PaymentOutputGuardHandler.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol, plasma_framework/contracts/src/exits/payment/spendingConditions/PaymentOutputToPaymentTxCondition.sol, plasma_framework/package-lock.json, plasma_framework/package.json, plasma_framework/test/src/exits/payment/PaymentProcessInFlightExit.test.js
- scan through all files in `src/exit/payment` and see if there is space for adding docuementation
- remove `IPaymentSPendingCondition` as it's leftover
ref: https://github.com/omisego/plasma-contracts/issues/284
=> 284 document improvement for `src/exit/payment`

plasma_framework/contracts/src/framework/utils/ExitPriority.sol
Made changes to the documentation and linked the discussion from #303, in order to make it clear what do the values come from.
Closes #316
=> Update exit priority documentation

plasma_framework/contracts/src/framework/BlockController.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/contracts/src/framework/PlasmaFramework.sol, plasma_framework/contracts/src/framework/Protocol.sol, plasma_framework/contracts/src/framework/interfaces/IExitProcessor.sol, plasma_framework/contracts/src/framework/models/BlockModel.sol, plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/contracts/src/framework/registries/VaultRegistry.sol, plasma_framework/contracts/src/framework/utils/ExitPriority.sol, plasma_framework/contracts/src/framework/utils/PriorityQueue.sol, plasma_framework/contracts/src/framework/utils/Quarantine.sol, plasma_framework/contracts/src/transactions/PaymentTransactionModel.sol, plasma_framework/contracts/src/transactions/WireTransaction.sol, plasma_framework/contracts/src/transactions/eip712Libs/PaymentEip712Lib.sol, plasma_framework/contracts/src/transactions/outputs/PaymentOutputModel.sol, plasma_framework/contracts/src/utils/IsDeposit.sol, plasma_framework/contracts/src/utils/TxPosLib.sol, plasma_framework/contracts/src/utils/UtxoPosLib.sol, plasma_framework/contracts/src/vaults/Erc20Vault.sol, plasma_framework/contracts/src/vaults/EthVault.sol, plasma_framework/contracts/src/vaults/Vault.sol, plasma_framework/contracts/src/vaults/verifiers/Erc20DepositVerifier.sol, plasma_framework/contracts/src/vaults/verifiers/EthDepositVerifier.sol, plasma_framework/contracts/src/vaults/verifiers/IErc20DepositVerifier.sol, plasma_framework/contracts/src/vaults/verifiers/IEthDepositVerifier.sol, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js
closes #284 (last part of this)
=> 284 document improvement

plasma_core/utils/eip712_struct_hash.py, plasma_framework/contracts/src/transactions/eip712Libs/PaymentEip712Lib.sol, plasma_framework/test/helpers/paymentEip712.js
well, as title.
Also a gentle nudge to maybe use (if exists) a sol/js lib for eip712, or roll some rudimentary tool like `elixir-omg` to at least somewhat reduce the chance of such errors.
=> fix: remove superfluous space in the eip712 types

plasma_framework/migrations/6_output_results.js
elixir-omg need the output to run their service
=> chore: output 'plasma_framework_tx_hash' and 'authority_address' in migration

plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouterArgs.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouterArgs.sol
Just some tidying and specifying which arguments to exit game routers are optional (I hope I got them right).
=> docs: groom and clarify the optional arguments of routers

README.md
Fix the awkward wording. Forgot to push it last night.
=> Fix the english

plasma_framework/contracts/src/vaults/EthVault.sol
=> refactor: remove unused variable in EthVault

contracts/RootChain.sol, tests/contracts/root_chain/test_process_exits.py
The PR provides required fixes to original `RootChain` contract related to wrong priority of IFE with a deposit.
Detailed info can be found in the following issue: #216.
=> IFE with deposit tx has wrong priority

plasma_framework/test/src/exits/payment/PaymentChallengeStandardExit.test.js
- Bumps test coverage for PaymentChalengeStandardExit to 100%
References #389
=> test: improve test coverage for PaymentChalengeStandardExit

plasma_framework/docs/integration-docs/integration-doc.md
- Add documentation on the part of `upgrading the framework`.
=> docs: [integ-doc] upgrading the framework

plasma_framework/test/src/exits/payment/PaymentExitGame.test.js
Improves coverage for `PaymentExitGame`.
References #389
=> refactor: improve test coverage for PaymentExitGame

README.md, plasma_framework/migrations/config.js
https://github.com/omisego/plasma-contracts/issues/408
=> min exit period via env var

plasma_framework/contracts/src/transactions/WireTransaction.sol, plasma_framework/test/src/transactions/WireTransaction.test.js, plasma_framework/test/src/vaults/EthVault.test.js
=> test: bump test coverage of WireTransaction and Vault to 100%

plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartInFlightExit.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/docs/contracts/PaymentChallengeIFEInputSpent.md, plasma_framework/docs/contracts/PaymentChallengeIFENotCanonical.md, plasma_framework/docs/contracts/PaymentChallengeIFEOutputSpent.md, plasma_framework/docs/contracts/PaymentInFlightExitRouter.md, plasma_framework/docs/contracts/PaymentPiggybackInFlightExit.md, plasma_framework/docs/contracts/PaymentStartInFlightExit.md, plasma_framework/docs/integration-docs/integration-doc.md, plasma_framework/test/src/exits/payment/PaymentChallengeIFEOutputSpent.test.js
=> feat: index events by transaction hash

plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol, plasma_framework/docs/contracts/PaymentStandardExitRouter.md
=> Remove payable from challenge standard exit

plasma_framework/contracts/src/exits/payment/routers/PaymentStandardExitRouter.sol, plasma_framework/docs/integration-docs/integration-doc.md
=> docs: add integration docs for challenging standard exit

plasma_framework/docs/design/payment-game-implementation-v1.md
- Add section for `deleteInFlightExit`
- Update the description after change for issue #470
=> docs: update with changes on deleteIFE and processIFE

plasma_framework/docs/design/add-new-tx-type-check-lists.md
This adds a doc for the check list when adding or designing new tx types.
- I am putting many reviewers for this to make sure nothing is missed
- Was collecting from: 
- https://github.com/omisego/docs/issues/27
- https://github.com/omisego/plasma-contracts/issues/194
=> docs: add new tx type check list

plasma_framework/contracts/src/exits/payment/PaymentExitGameArgs.sol, plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_start_in_flight_exit.py, plasma_framework/python_tests/tests/contracts/root_chain/test_start_standard_exit.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py
The following changes enable starting IFE tests.
Refers #150.
=> Python tests - start IFE 

plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_piggyback_in_flight_exit.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/python_tests/tests/contracts/root_chain/test_start_standard_exit.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py
The following PR introduces changes required to run tests of piggybacking an IFE and some minor refactors.
=> 150 piggybacking IFE

plasma_framework/contracts/src/framework/registries/ExitGameRegistry.sol, plasma_framework/test/src/framework/ExitGameController.test.js, plasma_framework/test/src/framework/registries/ExitGameRegistry.test.js, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js
=> Increase exit game quarantine period to 4

plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_challenge_in_flight_exit_input_spent.py, plasma_framework/python_tests/tests/contracts/root_chain/test_challenge_in_flight_exit_output_spent.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py
This batch of tests is focused on challenging inputs and outputs of IFEs.
=> 150 challenge ife input output

plasma_framework/python_tests/tests/contracts/priority_queue/test_priority_queue.py
Latest release of ganache-cli v6.8.1 breaks our CI as the gas changed. This PR re-experiment and recalculate the gas for priority queue with new ganache-cli. Also breaks `op_cost` function into `op_cost_insert` and `op_cost_del` as they have different costs.
I round the result up a bit when putting number in the formula to be not so strict on the value.
ref: https://github.com/omisego/plasma-contracts/pull/550#issuecomment-571870441
The following states the min and max gas for each 2^depth ~ 2^(depth +1), n is the amount of elements in the priority queue:
```
>>>>>> test_priority_queue_worst_case_gas_cost >>>>>>>
>>>> INSERT GAS >>>>>>
n: 2 max gas:  71462 min gas: 71462
n: 4 max gas:  81077 min gas: 71462
n: 8 max gas:  90692 min gas: 81077
n: 16 max gas:  100307 min gas: 90692
n: 32 max …
```
=> fix: priority queue gas calcuation for new ganache-cli

plasma_framework/docs/integration-docs/integration-doc.md
=> docs: add fees section to integration docs

plasma_framework/migrations/8_deploy_dev_contracts.js, plasma_framework/migrations/9_output_results.js
as title. To be used in https://github.com/omisego/elixir-omg/issues/901
=> feat: include MerkleWrapper deployment in dev contracts migration

plasma_framework/docs/integration-docs/integration-doc.md
closes #544
closes #548
closes #539 
- add detail on getting vault address via vaultId
- add detail on getting exit game address via tx type
- fix the description of getting bond value from `PaymentExitGame` instead of `PlasmaFramework`
- add section on process IFE
- add section on delete IFE
=> [Integ-doc] Be more specific on each contracts

plasma_framework/contracts/mocks/exits/SpyPlasmaFrameworkForExitGame.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentInFlightExitRouterMock.sol, plasma_framework/contracts/mocks/exits/payment/routers/PaymentStandardExitRouterMock.sol, plasma_framework/contracts/mocks/framework/DummyExitGame.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessStandardExit.sol, plasma_framework/contracts/src/framework/ExitGameController.sol, plasma_framework/docs/contracts/ExitGameController.md, plasma_framework/docs/contracts/PaymentInFlightExitRouter.md, plasma_framework/docs/contracts/PaymentProcessInFlightExit.md, plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/test/src/exits/payment/controllers/PaymentProcessInFlightExit.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentProcessStandardExit.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentStartStandardExit.test.js, plasma_framework/test/src/framework/ExitGameController.test.js
Closes https://github.com/omisego/security-issues/issues/13
=> fix: fix broken canonicity in IFE processing

CHANGELOG.md, plasma_framework/package-lock.json, plasma_framework/package.json
- change log for release 1.0.4
- bump package version
=> chore: release 1.0.4

.circleci/config.yml, plasma_framework/package-lock.json, plasma_framework/package.json
closes: #653 
- remove the "next" version of hdwallet-provider
- [CircleCI job](https://app.circleci.com/pipelines/github/omgnetwork/plasma-contracts/2266/workflows/d6958190-e372-4892-a8a5-6cac3527f3ca/jobs/11860/steps) deployed the contract with [this commit](https://github.com/omgnetwork/plasma-contracts/pull/655/commits/76a0b0b28885c96128bd717b6902493673559cd3) temporary removing the filter of branch.
=> hdwallet version upgrade

plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py
hopefully closes:  https://github.com/omgnetwork/plasma-contracts/issues/606
=> fix: flaky python test

plasma_framework/contracts/src/framework/BlockController.sol, plasma_framework/docs/contracts/BlockController.md, plasma_framework/migrations/20_deploy_plasma_framework.js, plasma_framework/package-lock.json, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py, plasma_framework/test/src/framework/BlockController.test.js, plasma_framework/test/src/vaults/Erc20Vault.test.js, plasma_framework/test/src/vaults/EthVault.test.js
some background: https://github.com/omgnetwork/plasma-contracts/pull/649#discussion_r465524336
=> rem child chain activation

plasma_framework/contracts/mocks/exits/payment/routers/PaymentInFlightExitRouterMock.sol, plasma_framework/contracts/mocks/utils/ExitBountyWrapper.sol, plasma_framework/contracts/src/exits/payment/PaymentExitDataModel.sol, plasma_framework/contracts/src/exits/payment/PaymentExitGame.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentPiggybackInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentProcessInFlightExit.sol, plasma_framework/contracts/src/exits/payment/controllers/PaymentStartStandardExit.sol, plasma_framework/contracts/src/exits/payment/routers/PaymentInFlightExitRouter.sol, plasma_framework/contracts/src/exits/utils/ExitBounty.sol, plasma_framework/python_tests/testlang/testlang.py, plasma_framework/python_tests/tests/contracts/root_chain/test_process_exits.py, plasma_framework/python_tests/tests/tests_utils/plasma_framework.py, plasma_framework/test/endToEndTests/PaymentInFlightExit.e2e.test.js, plasma_framework/test/src/exits/payment/PaymentInFlightExitModelUtils.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFEInputSpent.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFENotCanonical.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentChallengeIFEOutputSpent.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentDeleteInFlightExit.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentPiggybackInFlightExitOnInput.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentPiggybackInFlightExitOnOutput.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentProcessInFlightExit.test.js, plasma_framework/test/src/exits/payment/controllers/PaymentProcessStandardExit.test.js, plasma_framework/test/src/exits/utils/BountySize.test.js
Reverts omgnetwork/plasma-contracts#682 
Reverting to squash all the Exit Bounty changes together and have it on a new PR
=> Revert "[Process Exit Bounty] Add process exit bounty for IFE"

.circleci/config.yml, plasma_framework/package-lock.json, plasma_framework/package.json
fixes vault start issue
```
Error: getaddrinfo ENOTFOUND vault_server vault_server:8200
```
=> fix: deployment with multisig and vault

plasma_framework/contracts/poc/fast_exits/Quasar.sol, plasma_framework/test/endToEndTests/QuasarExit.e2e.test.js
=> Expand IFE Claim challenge scenarios

plasma_framework/contracts/mocks/poc/QuasarPoolMock.sol, plasma_framework/contracts/poc/fast_exits/Quasar.sol, plasma_framework/test/endToEndTests/QuasarExit.e2e.test.js, plasma_framework/test/src/poc/fast_exits/Quasar.test.js, plasma_framework/test/src/poc/fast_exits/QuasarPool.test.js
waitingPeriod isn't used anymore
=> quasar: rem unused waiting period
